functional:
- Должна быть возможность зарегистрироваться 
- Должна быть возможность авторизоваться
- Должна быть возможность авторизоваться с помощью Github и Discord
- Должна быть возможность создать игру с ботом, другом, с другим зарегистрированным игроком 
- Должна быть возможность создания турнира
- Должна быть возможность выбора игры #Возможно надо удалить или оставить,но не писать тест
- Должна быть возможность отображения набора кода соперником # нужен ли тест? или можно дописать в тесты п 5?
- Должна быть рейтинг игроков в игре
- Должна быть возможность выбора языка программирования
- Должна быть возможность менять язык программирования во время игры
- Должна быть возможность выбрать уровень сложности в игре # нужен ли тест? или можно дописать в тесты п 5?
- Должна быть возможность выбрать язык описания задачи в игре 
- Должна быть возможность выбора длительности игры как на время, так и до победы или сдачи # нужен ли тест? или можно дописать в тесты п 5? не реализована игра до победы
- При выбросе из игры, возможность вернутся и продолжить играть
- Должна быть возможность наблюдать за игрой других игроков
- Должна быть возможность общения с другими игроками
- Должна быть возможность игры без регистрации на сайте (ограничена игрой с ботом)
non-functional:
- Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
- Сайт должен быть безопасным и защищать данные пользователя
- Сайт должен предоставлять доступ к  контенту с мобильных устройств
- Сайт должен быть протестирован на совместимость с последними версиями браузеров
- Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
- Сайт должен быть мультиязычным
- Шрифт - хорошо виден, читаем без лишних усилий, цвет фона не должен совпадать с цветом шрифта, наполнение должно быть комфортно для просмотра
